### ISSUE TITLE
Book availability

### ISSUE THREAD

**Issue by heraldiclily** [sudharsan13296/Hands-On-Meta-Learning-With-Python#1]
Hello @sudharsan13296,

I ordered your book " Hands On Meta Learning With-Python" one month ago, but I haven't been delivered yet. Unfortunately this github version is still missing some sections. Do you have any idea about the book finalization and availability to the public?

Best Regards,

**Comment by sudharsan13296** [comment]
Hi @YasminaJaafra 

The book is getting published within the end of this year 2018. You will get it soon in 2-3 days. Hoping you will like the book.

**Comment by sudharsan13296** [comment]
Hi @YasminaJaafra,

The book is published on 31st December 2018. You will get the book soon if you had preordered already. If not, you can order the book here: https://www.amazon.com/gp/product/B07KJJHYKF/ref=dbs_a_def_rwt_bibl_vppi_i2
