### ISSUE TITLE
The chapter three for Omniglot Character set classification using Prototypical Network

### ISSUE THREAD

**Issue by pringwong** [sudharsan13296/Hands-On-Meta-Learning-With-Python#4]
I have run several times, and I find that the network is not updated. Furthermore, the parameter reuse do not work in the network. It needs some modifications.

**Comment by pringwong** [comment]
The book is rough, and the code realization for relation network is wrong for the labels.

**Comment by Wang-yaole** [comment]
I got in this problem too   ... hope for some solution
